[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm install --prefix client --legacy-peer-deps && npm run build --prefix client"

[deploy]
startCommand = "node api/index.js"